# 报错机制

## 教程前说明

后面每个案例讲解前，会对所在案例的目录结构和相关文件说明，请按目录结构和代码参照阅读；

其他*教程前说明* 请参照 [*01基础使用和说明*](.01_基础使用和说明.md#教程前的说明) 内容。

------

### 路径载入错误

目录结构:

* `index.html`
* `js`
	* `sr.js`
	* `main.js`

code:

```javascript
sr.config({
    baseUrl: "js/"
});

//main.js
require('aa')
	.done(function(data){
		console.log(data);
	})
	.fail(function(e){
		console.log(e);
	});
```

打印结果：

```
Array[1]
	0: Object
      //在数组内的序号
	  no: 0
	  state: "error"
	  url: "js/aa.js"
	  __proto__: Object
	length: 1
	__proto__: Array[0]
```

说明：

因为 `aa` 是不存在的，在获取失败的情况下，会执行fail内的函数。

### 全局error监听

若在上一案例中添加以下代码，同样会得到错误反馈

```javascript
sr.error = function(data){
    console.log(data);
}
```

sr在加载资源上的错误，都会反馈在这个函数上。

`fail`错误监听并不是经常用，如果全部requre后都加fail反馈显得特别麻烦，如果只想针对加载资源错误做特殊反馈，将逻辑绑定在`sr.error`上就很合适了；

### defer拒绝信息

目录结构:

* `index.html`
* `js`
	* `sr.js`
	* `main.js`
    * `d1.js`

code:

```javascript
sr.config({
    baseUrl: "js/"
});

//main.js
require('d1')
	.done(function(data){
		console.log(data);
	})
	.fail(function(e){
		console.log('fail => ',e);
	});
    
sr.error = function(){
    console.log('srerror => ',e);
};
```

```javascript
//d1.js
defer(function(require,resolve,reject){
    setTimeout(function(){
        //注意不是resolve而是reject
        reject('haha good!');
    },1000);
});
```

打印结果：

```
fail => Array[1]
        0: Object
          data:"haha good!"
          no: 0
          state: "rejected"
          url: "js/aa.js"
          __proto__: Object
        length: 1
        __proto__: Array[0]
```

defer模块可使用`reject`方法反馈数据，而错误反馈在require后的fail函数内，并带上返回的数据在`data`字段里；

通过defer的reject反馈并不属于资源错误，所以不会触发全局的`sr.error`函数；